In [14]:
import pandas as pd
import matplotlib.pyplot as plt

In [15]:
df = pd.read_csv("cumulative.csv")
# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')
# Drop the null rows
df = df.dropna()
df.head()

,rowid,kepid,kepoi_name,kepler_name,koi_disposition,koi_pdisposition,koi_score,koi_fpflag_nt,koi_fpflag_ss,koi_fpflag_co,...,koi_steff_err2,koi_slogg,koi_slogg_err1,koi_slogg_err2,koi_srad,koi_srad_err1,koi_srad_err2,ra,dec,koi_kepmag
0,1,10797460,K00752.01,Kepler-227 b,CONFIRMED,CANDIDATE,1.000,0,0,0,...,-81.0,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347
1,2,10797460,K00752.02,Kepler-227 c,CONFIRMED,CANDIDATE,0.969,0,0,0,...,-81.0,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347
4,5,10854555,K00755.01,Kepler-664 b,CONFIRMED,CANDIDATE,1.000,0,0,0,...,-211.0,4.438,0.070,-0.210,1.046,0.334,-0.133,288.75488,48.226200,15.509
5,6,10872983,K00756.01,Kepler-228 d,CONFIRMED,CANDIDATE,1.000,0,0,0,...,-232.0,4.486,0.054,-0.229,0.972,0.315,-0.105,296.28613,48.224670,15.714
6,7,10872983,K00756.02,Kepler-228 c,CONFIRMED,CANDIDATE,1.000,0,0,0,...,-232.0,4.486,0.054,-0.229,0.972,0.315,-0.105,296.28613,48.224670,15.714

In [16]:
df.shape

(2269, 48)

In [17]:
df.describe()

,rowid,kepid,koi_score,koi_fpflag_nt,koi_fpflag_ss,koi_fpflag_co,koi_fpflag_ec,koi_period,koi_period_err1,koi_period_err2,...,koi_steff_err2,koi_slogg,koi_slogg_err1,koi_slogg_err2,koi_srad,koi_srad_err1,koi_srad_err2,ra,dec,koi_kepmag
count,2269.000000,2.269000e+03,2269.000000,2269.000000,2269.000000,2269.000000,2269.000000,2269.000000,2.269000e+03,2.269000e+03,...,2269.000000,2269.000000,2269.000000,2269.000000,2269.000000,2269.000000,2269.000000,2269.000000,2269.000000,2269.000000
mean,2311.372411,8.111183e+06,0.962256,0.009696,0.011459,0.002644,0.000441,26.628847,2.141043e-04,-2.141043e-04,...,-124.157338,4.409910,0.089992,-0.106000,1.068152,0.175446,-0.150149,290.954149,44.380666,14.342540
std,1716.602291,2.583776e+06,0.145710,0.098011,0.106454,0.051366,0.020993,51.383181,1.264071e-03,1.264071e-03,...,52.095882,0.235551,0.079001,0.064612,0.645425,0.143798,0.226256,4.756312,3.570394,1.221567
min,1.000000,7.574500e+05,0.000000,0.000000,0.000000,0.000000,0.000000,0.341842,2.700000e-08,-5.100000e-02,...,-712.000000,2.410000,0.000000,-0.748000,0.118000,0.000000,-4.943000,280.206600,36.577381,8.224000
25%,1063.000000,6.184894e+06,0.993000,0.000000,0.000000,0.000000,0.000000,5.035057,1.130000e-05,-1.230000e-04,...,-152.000000,4.285000,0.036000,-0.126000,0.808000,0.066000,-0.164000,287.297700,41.515049,13.660000
50%,1987.000000,8.355239e+06,1.000000,0.000000,0.000000,0.000000,0.000000,11.189571,3.670000e-05,-3.670000e-05,...,-111.000000,4.453000,0.065000,-0.105000,0.969000,0.160000,-0.091000,291.145200,44.337551,14.600000
75%,3204.000000,1.018702e+07,1.000000,0.000000,0.000000,0.000000,0.000000,25.433786,1.230000e-04,-1.130000e-05,...,-83.000000,4.557000,0.130000,-0.052000,1.202000,0.243000,-0.056000,294.831020,47.208031,15.261000
max,9541.000000,1.283487e+07,1.000000,1.000000,1.000000,1.000000,1.000000,1071.232624,5.100000e-02,-2.700000e-08,...,0.000000,5.274000,0.765000,0.000000,19.530000,2.551000,0.000000,301.720760,52.149132,17.475000

In [18]:
# make sure you have installed scikit-learn with PIP3

# Set features. This will also be used as your x values.
selected_features = df[['koi_period', 'koi_time0bk', 'koi_slogg', 'koi_srad', 'koi_kepmag']]

In [19]:
df.head()

,rowid,kepid,kepoi_name,kepler_name,koi_disposition,koi_pdisposition,koi_score,koi_fpflag_nt,koi_fpflag_ss,koi_fpflag_co,...,koi_steff_err2,koi_slogg,koi_slogg_err1,koi_slogg_err2,koi_srad,koi_srad_err1,koi_srad_err2,ra,dec,koi_kepmag
0,1,10797460,K00752.01,Kepler-227 b,CONFIRMED,CANDIDATE,1.000,0,0,0,...,-81.0,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347
1,2,10797460,K00752.02,Kepler-227 c,CONFIRMED,CANDIDATE,0.969,0,0,0,...,-81.0,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347
4,5,10854555,K00755.01,Kepler-664 b,CONFIRMED,CANDIDATE,1.000,0,0,0,...,-211.0,4.438,0.070,-0.210,1.046,0.334,-0.133,288.75488,48.226200,15.509
5,6,10872983,K00756.01,Kepler-228 d,CONFIRMED,CANDIDATE,1.000,0,0,0,...,-232.0,4.486,0.054,-0.229,0.972,0.315,-0.105,296.28613,48.224670,15.714
6,7,10872983,K00756.02,Kepler-228 c,CONFIRMED,CANDIDATE,1.000,0,0,0,...,-232.0,4.486,0.054,-0.229,0.972,0.315,-0.105,296.28613,48.224670,15.714

In [20]:
# install Tensorflow

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from tensorflow.keras.utils import to_categorical

#assign x and y values
X = df.drop("koi_disposition", axis=1)
y = df["koi_disposition"]


#split training and testing data

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=84)

#X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=84, stratify = y)
#x_train, x_test, y_train, y_test = train_test_split(y,test_size=0.33, random_state=42)

In [21]:

X_train.head()

,rowid,kepid,kepoi_name,kepler_name,koi_pdisposition,koi_score,koi_fpflag_nt,koi_fpflag_ss,koi_fpflag_co,koi_fpflag_ec,...,koi_steff_err2,koi_slogg,koi_slogg_err1,koi_slogg_err2,koi_srad,koi_srad_err1,koi_srad_err2,ra,dec,koi_kepmag
2988,2989,10266615,K00530.01,Kepler-587 b,CANDIDATE,1.000,0,0,0,0,...,-173.0,4.547,0.042,-0.168,0.864,0.214,-0.077,288.67068,47.399139,14.909
3297,3298,8193178,K00572.01,Kepler-187 c,CANDIDATE,1.000,0,0,0,0,...,-134.0,4.281,0.125,-0.125,1.233,0.220,-0.180,299.79645,44.089310,14.173
1420,1421,7765528,K01840.01,Kepler-972 b,CANDIDATE,1.000,0,0,0,0,...,-79.0,4.278,0.132,-0.108,1.240,0.213,-0.194,295.82870,43.425491,14.915
2056,2057,10018233,K02655.01,Kepler-1306 b,CANDIDATE,0.894,0,0,0,0,...,-82.0,4.442,0.072,-0.099,0.961,0.115,-0.086,294.47833,46.945862,15.243
2234,2235,8081905,K02619.01,Kepler-1292 b,CANDIDATE,1.000,0,0,0,0,...,-203.0,4.504,0.039,-0.208,0.963,0.289,-0.096,284.90573,43.949162,15.934

In [28]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from tensorflow.keras.utils import to_categorical

In [35]:

# # Scale your data
# from sklearn.preprocessing import StandardScaler

# X_scaler = MinMaxScaler().fit(X_train)
# X_train_scaled = X_scaler.transform(X_train)
# X_test_scaled = X_scaler.transform(X_test)

In [36]:
# from sklearn.svm import SVC 
# model = SVC(kernel='linear')
# model.fit(X_train_scaled, y_train)
# predictions = model.predict(X_test)